# http://www.b3.com.br/pt_br/market-data-e-indices/indices/indices-amplos/indice-brasil-100-ibrx-100-composicao-da-carteira.htm

CARTEIRA_IBOV = [
            "ALOS3.SA",
            "ABEV3.SA",
            "ASAI3.SA",
            "AURE3.SA",
            "AZZA3.SA",
            "B3SA3.SA",
            "BBSE3.SA",
            "BBDC3.SA",
            "BBDC4.SA",
            "BRAP4.SA",
            "BBAS3.SA",
            "BRKM5.SA",
            "BRAV3.SA",
            "BPAC11.SA",
            "CXSE3.SA",
            "CEAB3.SA",
            "CMIG4.SA",
            "COGN3.SA",
            "CPLE6.SA",
            "CSAN3.SA",
            "CPFE3.SA",
            "CMIN3.SA",
            "CURY3.SA",
            "CVCB3.SA",
            "CYRE3.SA",
            "DIRR3.SA",
            "ELET3.SA",
            "ELET6.SA",
            "EMBR3.SA",
            "ENGI11.SA",
            "ENEV3.SA",
            "EGIE3.SA",
            "EQTL3.SA",
            "FLRY3.SA",
            "GGBR4.SA",
            "GOAU4.SA",
            "HAPV3.SA",
            "HYPE3.SA",
            "IGTI11.SA",
            "IRBR3.SA",
            "ISAE4.SA",
            "ITSA4.SA",
            "ITUB4.SA",
            "KLBN11.SA",
            "RENT3.SA",
            "LREN3.SA",
            "MGLU3.SA",
            "POMO4.SA",
            "MBRF3.SA",
            "BEEF3.SA",
            "MOTV3.SA",
            "MRVE3.SA",
            "MULT3.SA",
            "NATU3.SA",
            "PCAR3.SA",
            "PETR3.SA",
            "PETR4.SA",
            "RECV3.SA",
            "PRIO3.SA",
            "PSSA3.SA",
            "RADL3.SA",
            "RAIZ4.SA",
            "RDOR3.SA",
            "RAIL3.SA",
            "SBSP3.SA",
            "SANB11.SA",
            "CSNA3.SA",
            "SLCE3.SA",
            "SMFT3.SA",
            "SUZB3.SA",
            "TAEE11.SA",
            "VIVT3.SA",
            "TIMS3.SA",
            "TOTS3.SA",
            "UGPA3.SA",
            "USIM5.SA",
            "VALE3.SA",
            "VAMO3.SA",
            "VBBR3.SA",
            "VIVA3.SA",
            "WEGE3.SA",
            "YDUQ3.SA",







][::-1]
